CREATE TABLE caller_reputation (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	caller_hash TEXT NOT NULL UNIQUE,
	status TEXT NOT NULL DEFAULT 'unknown',
	risk_score INTEGER NOT NULL DEFAULT 0,
	attempt_count INTEGER NOT NULL DEFAULT 1,
	first_seen TEXT DEFAULT CURRENT_TIMESTAMP,
	last_seen TEXT DEFAULT CURRENT_TIMESTAMP
);
